### ISSUE TITLE
Data available?

### ISSUE THREAD

**Issue by mezarafael** [VictimOfMaths/DeathsOfDespair#2]
https://github.com/VictimOfMaths/DeathsOfDespair/blob/4aff3312e8870011c578391455aa3e1d57cda085/APCCurvaturePlotUS.R#L13

Any chance you could share the CDC data here? Or provide more details on the source (eg, which is the Masters et al paper)?

Thanks a lot. Amazing plots,

**Comment by VictimOfMaths** [comment]
Hi Rafael,

The CDC Wonder database is publicly available/queryable here: https://wonder.cdc.gov/ucd-icd10.html

The Masters et al paper referenced is here: https://doi.org/10.1093/ije/dyx127 The ICD-10 code definitions are in the Supplementary Data

I've also uploaded the files to this repo.

Regards,

Colin
